# Generated by Django 5.0.6 on 2024-06-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_item_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
