# Generated by Django 5.0.6 on 2024-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_user_real_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(default='testemail@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
