# Generated by Django 5.0.6 on 2024-06-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
