# Generated by Django 5.0.6 on 2024-06-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_itemcondition_item_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
