# Generated by Django 5.0.6 on 2024-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_remove_user_email_address_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
