# Generated by Django 5.0.6 on 2024-07-22 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_item_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
