# Generated by Django 5.0.6 on 2024-07-23 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_alter_item_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
